### ISSUE TITLE
Correct answer was marked wrong

### ISSUE THREAD

**Issue by SeeeD** [timroes/lvlup-game#20]
Maybe you can have a look on this on your logfile? 
A colleague of mine submitted the answer "4" on the first question and it was marked wrong, but was the right answer. Maybe you can have a look on this

**Comment by timroes** [comment]
I guess this might be the same error as described in #4 

Most likely it was not sent to the server. A screenshot would be very helpful. If the answer was striked through red and the correct answer written in green below, this is really a (new) bug. If the answer was just written in gray and a correct answer written below, the given answer never hit the server (either socket.io package loss or e.g. the server has already closed the answer, when it received it from the client, perhaps because the question message took too long from server to client, so the client seemed to have more time, than it have).

I will close this in favor of #4. But if you can provide any more insights feel free to leave a comment in this or the other issue.

**Comment by SeeeD** [comment]
As I remember the answer was gray.
